// Loop Studio — EDITTRAX player embed transform. Pure string/DOM-plumbing
// module: no React, no fetch, no build step — every export is either a pure
// string transform (`buildEmbedSrcdoc`) or a best-effort read of a live
// iframe (`readLivePartLoops`), directly testable under node:test.
//
// WHY srcdoc + <base>: the player's engine reads its track config
// SYNCHRONOUSLY at parse time — `const numBoxes = parts.length` is a
// top-level statement in scroll_unlock.js:11, and script_unlocked.js starts
// building `Tone.Buffer` objects straight off `parts` as soon as it runs.
// There is no "postMessage after load" hook to hang a rebuild off of: the
// `parts` / `bpm` / `presets` / `downloadName` / `boxHeight` /
// `reverseScrolling` globals (normally defined by track.js) must already
// exist in the DOM before scroll_unlock.js and script_unlocked.js execute.
// Embedding the player as a srcdoc iframe lets the parent inline a generated
// config script in track.js's exact slot, so by the time the browser reaches
// `<script src="scroll_unlock.js">` the globals are already there. A
// `<base href="...">` tag makes every relative template asset (css, fonts,
// svg, engine js, cover.jpg) resolve against the served template directory
// even though the HTML text itself lives in a srcdoc attribute with no real
// URL of its own.
//
// The track-config script text itself (the `trackConfigScript` argument) is
// generated by ./edittrax-export.js — this module only splices it in.

const HEAD_TAG_RE = /<head(\s[^>]*)?>/i;
const TRACK_JS_SCRIPT_RE = /<script\b[^>]*\bsrc\s*=\s*(["'])track\.js\1[^>]*>\s*<\/script\s*>/i;

/**
 * Transform the EDITTRAX player's index.html for srcdoc embedding.
 *
 * @param {object} args
 * @param {string} args.indexHtml - the player template's raw index.html text.
 * @param {string} args.baseHref - href for the injected <base> tag (e.g. "/edittrax-player/").
 * @param {string} args.trackConfigScript - generated track.js body (from ./edittrax-export.js),
 *   spliced in as an inline <script> in place of <script src="track.js"></script>.
 * @returns {string} the transformed HTML, ready to assign to an iframe's `srcdoc`.
 */
export function buildEmbedSrcdoc({ indexHtml, baseHref, trackConfigScript }) {
  const source = String(indexHtml ?? '');

  const headMatch = source.match(HEAD_TAG_RE);
  if (!headMatch) {
    throw new Error(
      'buildEmbedSrcdoc: no <head> tag found in indexHtml — the player template '
      + 'structure changed; refusing to emit a broken embed.',
    );
  }
  const headEnd = headMatch.index + headMatch[0].length;
  const withBase = `${source.slice(0, headEnd)}\n<base href="${baseHref}">${source.slice(headEnd)}`;

  if (!TRACK_JS_SCRIPT_RE.test(withBase)) {
    throw new Error(
      'buildEmbedSrcdoc: no <script src="track.js"></script> tag found in indexHtml — '
      + 'the player template structure changed; refusing to emit a broken embed.',
    );
  }
  const withConfig = withBase.replace(
    TRACK_JS_SCRIPT_RE,
    `<script>\n${trackConfigScript}\n</script>`,
  );

  return withConfig;
}

/**
 * Best-effort read of the live loop counts the player's own UI has set, via
 * `iframeEl.contentWindow.parts` (same-origin srcdoc, so this is a direct
 * synchronous read — no postMessage bridge). Never throws: any failure
 * (missing/cross-origin contentWindow, missing/empty/malformed `parts`)
 * resolves to `null` so callers can fall back to their own last-known state.
 *
 * @param {*} iframeEl - the mounted iframe element (or a stub with the same shape).
 * @returns {number[]|null}
 */
export function readLivePartLoops(iframeEl) {
  try {
    const win = iframeEl && iframeEl.contentWindow;
    if (!win) return null;

    const parts = win.parts;
    if (!Array.isArray(parts) || parts.length === 0) return null;

    const loops = parts.map((part) => Number(part && part.loop));
    if (loops.some((n) => !Number.isFinite(n))) return null;

    return loops;
  } catch {
    return null;
  }
}
