// Payload config — exact-mirror overlay model. Generated by the HITLOOP Site
// Recreate pipeline (services/site-clone/build-cms.mjs).
//
// Each page = the ORIGINAL mirrored HTML (templates/<file>.html, tokens where
// editable content was) + a flat list of slots (text or image) holding the
// live values. Editing a slot in /admin changes the rendered site without
// touching the theme, so the site keeps looking exactly like the original.
//
// The sqlite adapter is libSQL-based: local file DB by default, hosted Turso
// via DATABASE_URI/DATABASE_AUTH_TOKEN in .env (then `npm run seed`).
import path from 'path';
import { fileURLToPath } from 'url';
import { buildConfig } from 'payload';
import { sqliteAdapter } from '@payloadcms/db-sqlite';
import { lexicalEditor } from '@payloadcms/richtext-lexical';
import { vercelBlobStorage } from '@payloadcms/storage-vercel-blob';
import sharp from 'sharp';

import { notifyHitloop } from './hooks/notify-hitloop';

// Owned-tier change tracking: any pages/media save notifies HITLOOP (no-op
// unless the hosting deploy set the webhook env).
const contentChangeHooks = {
  afterChange: [() => notifyHitloop()],
  afterDelete: [() => notifyHitloop()],
};

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);

export default buildConfig({
  admin: {
    user: 'users',
    // Live Preview: editing a page shows the REAL site alongside the fields.
    // SITE_ORIGIN is set by the hosting deploy; local dev falls back to the
    // dev server itself.
    livePreview: {
      url: ({ data }) => {
        const origin = process.env.SITE_ORIGIN || 'http://localhost:3100';
        const slug = data?.slug && data.slug !== 'home' ? `/${data.slug}` : '/';
        return `${origin}${slug}`;
      },
      collections: ['pages'],
    },
  },
  collections: [
    {
      slug: 'users',
      auth: true,
      admin: { useAsTitle: 'email' },
      fields: [],
    },
    {
      slug: 'media',
      admin: { description: 'Upload replacement images here, then pick them on a page\'s image slot.' },
      hooks: contentChangeHooks,
      access: { read: () => true },
      upload: {
        staticDir: path.resolve(dirname, '../public/media'),
      },
      fields: [{ name: 'alt', type: 'text' }],
    },
    {
      slug: 'pages',
      hooks: contentChangeHooks,
      access: { read: () => true },
      admin: {
        useAsTitle: 'title',
        defaultColumns: ['title', 'slug'],
        description: 'Every text and image from the original site, editable in place. The design/theme is preserved exactly.',
      },
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'slug', type: 'text', required: true, unique: true, admin: { readOnly: true } },
        { name: 'sourceFile', type: 'text', required: true, admin: { hidden: true } },
        {
          name: 'slots',
          type: 'array',
          admin: { description: 'Edit any value — the site updates immediately. Image slots: upload a replacement under "media", then select it.' },
          fields: [
            { name: 'key', type: 'text', required: true, admin: { hidden: true } },
            { name: 'kind', type: 'select', options: ['text', 'image'], required: true, admin: { hidden: true } },
            { name: 'label', type: 'text', admin: { readOnly: true } },
            { name: 'value', type: 'textarea' },
            { name: 'srcset', type: 'text', admin: { hidden: true } },
            {
              name: 'media',
              type: 'upload',
              relationTo: 'media',
              admin: { condition: (_data: any, siblingData: any) => siblingData?.kind === 'image' },
            },
          ],
        },
      ],
    },
  ],
  globals: [],
  // Hosted (serverless) deploys have no writable disk — admin image uploads
  // go to Vercel Blob when the token env exists (provisioned by
  // deploy-cms.mjs). Local/downloaded runs keep plain disk storage.
  plugins: [
    vercelBlobStorage({
      enabled: Boolean(process.env.BLOB_READ_WRITE_TOKEN),
      collections: { media: true },
      token: process.env.BLOB_READ_WRITE_TOKEN || '',
    }),
  ],
  editor: lexicalEditor(),
  secret: process.env.PAYLOAD_SECRET || 'dev-secret-change-me',
  typescript: { outputFile: path.resolve(dirname, 'payload-types.ts') },
  db: sqliteAdapter({
    client: {
      url: process.env.DATABASE_URI || 'file:./{{PROJECT}}.db',
      authToken: process.env.DATABASE_AUTH_TOKEN || undefined,
    },
  }),
  sharp,
});
