// Payload config — exact-mirror overlay model. Generated by the HITLOOP Site
// Recreate pipeline (services/site-clone/build-cms.mjs).
//
// Each page = the ORIGINAL mirrored HTML (templates/<file>.html, tokens where
// editable content was) + a flat list of slots (text or image) holding the
// live values. Editing a slot in /admin changes the rendered site without
// touching the theme, so the site keeps looking exactly like the original.
//
// The sqlite adapter is libSQL-based: local file DB by default, hosted Turso
// via DATABASE_URI/DATABASE_AUTH_TOKEN in .env (then `npm run seed`).
import path from 'path';
import { fileURLToPath } from 'url';
import { buildConfig } from 'payload';
import { sqliteAdapter } from '@payloadcms/db-sqlite';
import { lexicalEditor } from '@payloadcms/richtext-lexical';
import sharp from 'sharp';

const filename = fileURLToPath(import.meta.url);
const dirname = path.dirname(filename);

export default buildConfig({
  admin: { user: 'users' },
  collections: [
    {
      slug: 'users',
      auth: true,
      admin: { useAsTitle: 'email' },
      fields: [],
    },
    {
      slug: 'media',
      admin: { description: 'Upload replacement images here, then pick them on a page\'s image slot.' },
      access: { read: () => true },
      upload: {
        staticDir: path.resolve(dirname, '../public/media'),
      },
      fields: [{ name: 'alt', type: 'text' }],
    },
    {
      slug: 'pages',
      access: { read: () => true },
      admin: {
        useAsTitle: 'title',
        defaultColumns: ['title', 'slug'],
        description: 'Every text and image from the original site, editable in place. The design/theme is preserved exactly.',
      },
      fields: [
        { name: 'title', type: 'text', required: true },
        { name: 'slug', type: 'text', required: true, unique: true, admin: { readOnly: true } },
        { name: 'sourceFile', type: 'text', required: true, admin: { hidden: true } },
        {
          name: 'slots',
          type: 'array',
          admin: { description: 'Edit any value — the site updates immediately. Image slots: upload a replacement under "media", then select it.' },
          fields: [
            { name: 'key', type: 'text', required: true, admin: { hidden: true } },
            { name: 'kind', type: 'select', options: ['text', 'image'], required: true, admin: { hidden: true } },
            { name: 'label', type: 'text', admin: { readOnly: true } },
            { name: 'value', type: 'textarea' },
            { name: 'srcset', type: 'text', admin: { hidden: true } },
            {
              name: 'media',
              type: 'upload',
              relationTo: 'media',
              admin: { condition: (_data: any, siblingData: any) => siblingData?.kind === 'image' },
            },
          ],
        },
      ],
    },
  ],
  globals: [],
  editor: lexicalEditor(),
  secret: process.env.PAYLOAD_SECRET || 'dev-secret-change-me',
  typescript: { outputFile: path.resolve(dirname, 'payload-types.ts') },
  db: sqliteAdapter({
    client: {
      url: process.env.DATABASE_URI || 'file:./{{PROJECT}}.db',
      authToken: process.env.DATABASE_AUTH_TOKEN || undefined,
    },
  }),
  sharp,
});
