# {{SITE_NAME}} — your site, editable

Generated by HITLOOP Site Recreate from {{SOURCE_URL}}.

This is the SAME site as your static recreation — identical design, pages, and
images — with an admin panel added. Every text and image was catalogued as an
editable "slot"; the site renders your original HTML with your edits injected,
so the look never drifts from the original.

Payload 3 + Next.js, database on libSQL (local file by default, Turso-ready).

## Quickstart

```bash
npm install
npm run seed     # loads your site's original content into the CMS
npm run dev      # http://localhost:3100
```

- **Your site:** http://localhost:3100
- **Edit it:** http://localhost:3100/admin
  - Login: `admin@{{PROJECT}}.local` / `changeme123` — change this after first login.

Run every command from this folder (the database path is relative to it).

## How editing works

- **Pages** → pick a page → **Slots**: every text and image from the original
  site, in page order, labeled with a preview of its content. Change a value,
  save, refresh the site — done.
- **Images**: upload the new image under **Media**, then select it on the
  image slot you want to replace.
- `npm run seed` again = reset every slot back to the original site's content.

## Move the database to Turso (cloud)

```bash
turso db create {{PROJECT}}
turso db show {{PROJECT}} --url        # -> DATABASE_URI
turso db tokens create {{PROJECT}}     # -> DATABASE_AUTH_TOKEN
```

Put both values in `.env`, then `npm run seed` once to populate the cloud DB.

## Going live

Ready for a real domain + hosting? Your HITLOOP dashboard has a "Contact Your
Human" button on the Site Recreate card — DNS transfer and hosting are handled
for you.
