#!/usr/bin/env node
// vendor-api-lib.mjs — Phase 3 packaging fix (STUDIO-DETERMINISTIC-FINAL-
// RENDER-SONNET-HANDOFF.md). Copies the EXACT, closed dependency closure
// proof-render-worker.mjs needs from `api/_lib/` into `services/studio-
// render/vendor/api-lib/`, so the files are service-local (tracked in git,
// present on disk regardless of how the container gets built) instead of
// reaching outside this service's own directory.
//
// SAME rationale as scripts/vendor-elements.mjs (read that file's own header
// first — this is the identical pattern, second dependency closure): the
// worker previously required `../../api/_lib/proof-render-jobs.cjs` /
// `proof-render-artifacts.cjs` by a relative path that reaches OUTSIDE
// `services/studio-render/`, which can never resolve inside a
// `--source .`-built image whose Dockerfile COPYs an explicit, closed file
// list (never `COPY . .`).
//
// WHY a SEPARATE script/vendor dir from vendor-elements.mjs, not one merged
// script: this is a genuinely different dependency graph (Firestore/Storage
// job-queue modules, not pure browser-independent scene-recipe logic) with
// its own DI-seam contract (`__setTestContext`) that every worker/
// proof-server/drain-script test relies on targeting the SAME vendored
// module instance the production code actually imports (see
// __tests__/proof-render-worker.test.mjs's own require path) — keeping the
// two vendoring concerns in separate, independently-regenerable scripts
// keeps that contract obvious rather than folding two different kinds of
// "why this file is vendored" into one file list.
//
// Vendored files ARE committed to git and byte-compared against the real
// source by __tests__/vendor-api-lib.test.mjs on every test run — see
// vendor-elements.mjs's own comment for the full "committed mirror,
// regenerated by an explicit sync step, tested for drift" rationale (same
// pattern, not repeated here). `deploy-cloud-run-proof.sh` re-runs this
// script right before deploying, same belt-and-suspenders guarantee
// deploy-cloud-run.sh already established for vendor-elements.mjs.

import { existsSync, mkdirSync, copyFileSync, readdirSync, rmSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SERVICE_DIR = path.resolve(__dirname, '..');
const SOURCE_DIR = path.resolve(SERVICE_DIR, '../../api/_lib');
const TARGET_DIR = path.resolve(SERVICE_DIR, 'vendor/api-lib');

// proof-render-worker.mjs's full, closed Firestore/Storage dependency
// closure (verified by direct inspection: firebase-admin.cjs imports only
// the `firebase-admin` npm package + node builtins; proof-render-jobs.cjs
// and proof-render-artifacts.cjs each import ONLY `./firebase-admin.cjs`
// plus node builtins/npm packages — no other api/_lib file). Deliberately
// an EXPLICIT file list, not a whole-directory copy, same reasoning as
// vendor-elements.mjs's own VENDORED_FILES.
export const VENDORED_FILES = [
  'firebase-admin.cjs',
  'proof-render-jobs.cjs',
  'proof-render-artifacts.cjs',
  // Slice F2 — pinned device-screen stills: imports ONLY ./firebase-admin.cjs
  // + node builtins, same closed closure as the two modules above.
  'studio-screen-stills.cjs',
];

/** Same `targetDir` override seam as vendorElements — see that function's own comment for the concurrent-test-isolation rationale. */
export function vendorApiLib({ log = () => {}, targetDir = TARGET_DIR } = {}) {
  rmSync(targetDir, { recursive: true, force: true });
  mkdirSync(targetDir, { recursive: true });
  for (const file of VENDORED_FILES) {
    const from = path.join(SOURCE_DIR, file);
    const to = path.join(targetDir, file);
    if (!existsSync(from)) throw new Error(`vendor-api-lib: source file missing: ${from}`);
    copyFileSync(from, to);
    log(`vendored ${file}`);
  }
  const extra = readdirSync(targetDir).filter((f) => !VENDORED_FILES.includes(f));
  if (extra.length) throw new Error(`vendor-api-lib: unexpected leftover file(s) in ${targetDir}: ${extra.join(', ')}`);
  return { sourceDir: SOURCE_DIR, targetDir, files: VENDORED_FILES };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const result = vendorApiLib({ log: (msg) => console.log(msg) });
  console.log(`Vendored ${result.files.length} file(s) from ${result.sourceDir} into ${result.targetDir}`);
}
