// art-recipe.mjs — Slice 4a (Studio Roadmap, docs/plans/STUDIO-ROADMAP-NEXT-
// PHASE-SONNET-HANDOFF.md) — a PURE normalize/validate boundary for the
// "art-scene-v2" Proof recipe. This module does not render anything: it
// takes an untrusted payload (ClothStudio.jsx's browser captureSceneRecipe()
// output, or a cloud template's stored recipe — api/_lib/studio-templates.cjs)
// and returns a fully validated, browser-independent recipe object that a
// LATER slice (4c+) can hand to an actual render pipeline.
//
// Explicitly OUT of scope here (per the Slice 4a approval): no Cloud Run
// code, no GPU/headless-browser driving, no FFmpeg/ffprobe, no job queue, no
// API route, no network/Storage/Firestore access of any kind. This file has
// zero side effects and zero I/O — every export is a pure function over its
// arguments.
//
// This is a NEW, PARALLEL module living alongside the existing Video Promo
// pipeline (recipe.mjs/scene.mjs/render.mjs/server.mjs in this same
// directory) — see docs/plans/ORIGINAL-STUDIO-CINEMATIC-SETS-4K-PLAN.md's
// "Suggested code organization". Those files describe a completely different
// recipe format (a live URL + camera dive around a 3D device mockup) and are
// not read, imported, or modified by anything in this file.
//
// ── Why this module keeps its own copies of ClothStudio.jsx's enum lists ──
// ClothStudio.jsx is a 4700+-line 'use client' React component full of
// three.js/browser-only code; none of its enum constants (PERF_LEVELS,
// FINISHES, MATERIAL_PRESETS, LIGHT_TEMPLATES, FRAME_PRESETS, ENV_PRESETS,
// FX_PRESETS, SCENE_PRESETS, CLOTH_ASPECTS, VIDEO_FORMATS, PIN_MODES,
// TREATMENTS, BUILTIN_ARTWORKS, PRIMARY_ELEMENT_ID) are exported, and
// importing/executing that whole file from a plain Node service isn't
// viable. Real SANITIZER LOGIC (sanitizeMat/Phys/Anim/Cam/Glass/ShotCam/
// DiffusionCamera/Fx/LightCans/ElementLocks/Vec3) is reused verbatim, via a
// real import, from elements/scene-recipe.js — nothing there is duplicated.
// extraInstances validation (catalog membership, per-field clamping, id
// dedup) is likewise reused verbatim from elements/scene-elements.js +
// elements/schema.js + elements/catalog.js + elements/placement.js +
// elements/quality.js + elements/intensity.js — all confirmed side-effect-
// free, browser-independent modules (no `window`/`document`, no three.js
// imports) safe to import from this Cloud Run service.
//
// Only the plain ENUM VALUE LISTS below (id strings ClothStudio.jsx declares
// locally and never exports) are duplicated, because there is nothing to
// import. __tests__/art-recipe.test.mjs's "enum parity with ClothStudio.jsx"
// test reads ClothStudio.jsx's SOURCE TEXT (never imports/executes it) and
// asserts every list below still matches what's actually declared there — a
// future ClothStudio.jsx enum change that isn't mirrored here fails that
// test immediately instead of silently drifting.
//
// ── Why these imports point at ./vendor/elements/, not app/dashboard/studio
// /elements/ directly (Slice 4a Codex re-review fix) ────────────────────────
// `deploy-cloud-run.sh` builds ONLY from this directory (`--source .`, after
// `cd`ing here), and the Dockerfile COPYs an explicit, closed file list —
// never `COPY . .`. A relative import reaching outside `services/studio-
// render/` (as this file originally had) can never resolve inside the real
// built container. `./vendor/elements/` is a service-local, committed,
// byte-for-byte mirror of the exact 9-file dependency closure above,
// produced by `scripts/vendor-elements.mjs` (same "committed mirror of a
// real source, regenerated by an explicit sync step" pattern this repo
// already uses for `ds-bundle/`). `__tests__/art-recipe.test.mjs`'s
// "vendor is in sync" tests fail immediately if a real `elements/*.js` file
// changes without the vendored copy being regenerated to match.
import {
  isFiniteNum, isHexColor, isBool, sanitizeVec3,
  sanitizeMat, sanitizePhys, sanitizeAnim, sanitizeCam, sanitizeGlass,
  sanitizeShotCam, sanitizeDiffusionCamera, sanitizeFx, sanitizeLightCans,
  sanitizeTshirtPrint,
} from './vendor/elements/scene-recipe.js';
import { restoreExtraInstances } from './vendor/elements/scene-elements.js';
import { OUTPUT_FORMATS as PLACEMENT_FORMATS } from './vendor/elements/placement.js';
import { LIVE_PREVIEW_TIERS } from './vendor/elements/quality.js';
import { MAX_EXTRA_INSTANCES } from './vendor/elements/catalog.js';
// Scene/background parity (Slice B/C) — the vendored ClothStudio scene
// tables, via the shared composition module (same file the capability check
// and renderer use, so allowlists can never diverge between them).
import { SCENE_PANO_IDS, GROUND_TEXTURE_IDS } from './art-scene-def.mjs';
// Device tables (Slice F1 P1 correction) — model/shell allowlists come from
// the SAME vendored factory tables the renderer resolves against, checked
// with Object.hasOwn (never a bare read: '__proto__'/'constructor'/
// 'toString' resolve truthy prototype values otherwise).
import { DEVICE_MODELS, DEVICE_SHELL_TEXTURES } from './vendor/elements/factories.js';

export const RECIPE_KIND = 'art-scene-v2';
export const RECIPE_SCHEMA_VERSION = 1;

// The one always-present, non-caller-controlled instance — ClothStudio.jsx's
// own hardcoded PRIMARY_ELEMENT_ID. Never accepted from input; exposed here
// only so a future renderer knows which id `extraInstances` must never
// collide with (restoreExtraInstances already enforces that).
export const PRIMARY_ELEMENT_ID = 'glass-petal-sphere-1';

// ── Duplicated enum lists (see header comment) ──────────────────────────────
export const PERF_LEVEL_IDS = ['high', 'medium', 'low'];
export const FINISHES = ['glossy', 'satin', 'matte'];
export const PIN_MODE_IDS = ['free-float', 'top-edge', 'top-corners', 'four-corners'];
export const MATERIAL_PRESET_IDS = [
  'black-cloth', 'holo-foil', 'oil-slick', 'chrome', 'silk', 'paper',
  'velvet-night', 'midnight-drama', 'neon-noir', 'gothic-pearl',
  'acid-rave', 'solar-flare', 'liquid-gold', 'chrome-storm',
  'candy-gloss', 'glacier', 'pearl-daylight', 'studio-white',
];
export const LIGHT_TEMPLATE_IDS = ['studio', 'single-spot', 'neon-cross', 'fire-ice', 'top-wash', 'club-floor'];
export const FRAME_PRESET_IDS = ['off', 'square', 'portrait', 'vertical', 'landscape'];
export const ENV_PRESET_IDS = ['room', 'sunset', 'dusk', 'hall', 'night'];
export const FX_PRESET_IDS = [
  'halftone-press', 'newsprint-1bit', 'riso-duotone', 'screenprint-lines', 'xerox-blowout',
  'cinema-bloom', 'cross-process', 'faded-archive', 'night-neon', 'studio-clean',
  'crt-broadcast', 'pixel-console', 'chromatic-glitch', 'vapor-grid', 'data-mosh',
  'solar-burn', 'kaleido-cathedral', 'acid-posterize', 'blueprint-cyanotype', 'chrome-emboss',
];
// Synced to ClothStudio.jsx's SCENE_PRESETS (2026-08-02, scene/background-
// parity tranche step 1 — the cinematic-sets/HDR work grew this from 8 to
// 79; the art-recipe.test.mjs enum-parity drift-guard enforces exact
// order/content). sceneId is still PROVENANCE-ONLY in this render pass:
// it only ever affects rendering once bgMode==='scene', which remains
// capability-gated ('background') until scene-background rendering itself
// lands. This sync stops a NEW preset's sceneId being silently rewritten
// to 'thriller' during normalization — honest provenance, no render change.
export const SCENE_PRESET_IDS = [
  'thriller', 'smoke-stage', 'neon-alley', 'deep-sea', 'retro-sunset', 'golden-hour',
  'desk-studio', 'suite-soft', 'suite-stage', 'loft-morning', 'loft-dream', 'loft-stage',
  'terminal-glass', 'terminal-rush', 'terminal-stage', 'venice-table', 'venice-dream', 'venice-stage',
  'dusk-table', 'dusk-mirage', 'dusk-stage', 'ballroom', 'ballroom-dream', 'midnight-table', 'midnight-stage',
  'white-cyc', 'ink-cyc',
  'cyber-platz', 'cyber-platz-rain', 'cyber-bund', 'cyber-bund-close', 'cyber-neon-lab', 'cyber-neon-haze',
  'cyber-grid', 'cyber-noir', 'cyber-alley', 'cyber-metro',
  'office-workshop', 'office-workshop-soft', 'office-metro-hall', 'office-metro-desk',
  'office-studio', 'office-studio-soft', 'office-royal', 'office-royal-grand',
  'dark-void', 'dark-ember', 'dark-courtyard', 'dark-courtyard-dream', 'dark-graphite', 'dark-onyx',
  'dark-shanghai', 'dark-neon-after',
  'light-sky', 'light-sky-dream', 'light-royal-air', 'light-white-studio', 'light-linen',
  'light-porcelain', 'light-morning-shop', 'light-gallery-hall',
  'abs-magma', 'abs-ultraviolet', 'abs-tealfog', 'abs-acid', 'abs-rose', 'abs-cobalt', 'abs-sandstorm',
  'abs-mint', 'abs-bloodbars', 'abs-arctic', 'abs-goldleaf', 'abs-noirfog', 'abs-cotton', 'abs-jade',
  'abs-royal', 'abs-solar',
  'candy-pop', 'gallery-white',
];
export const CLOTH_ASPECT_IDS = ['portrait', 'square', 'landscape'];
// Primary garment/element mode (ClothStudio.jsx clothShape state, ~L2938).
// art-scene.mjs only ever builds the flat 'sheet' cloth (buildCloth) — a
// 'tshirt'/'device' recipe rendered without gating would silently produce
// the WRONG primary shape, not just a missing feature. See checkCapabilities'
// 'clothShape' entry in art-render-validation.mjs.
export const CLOTH_SHAPE_IDS = ['sheet', 'tshirt', 'device'];
export const VIDEO_FORMAT_IDS = ['mp4', 'webm'];
export const TREATMENT_IDS = ['none', 'halftone', 'pixel', 'poster', 'threshold', 'duotone', 'chroma', 'scanline', 'riso', 'edges', 'solarize', 'crossproc', 'mirror'];
export const BUILTIN_ARTWORK_IDS = ['brock', 'viva-program'];
export const BG_MODES = ['scene', 'color', 'image', 'transparent'];
export const VIDEO_SECONDS_OPTIONS = [3, 5, 8, 10, 15];

const DEFAULT_ARTWORK_ID = 'brock';

// ── Defaults (mirrors ClothStudio.jsx's own useState initializers exactly —
// a minimal/empty input recipe must normalize to the SAME starting look the
// browser itself opens with). ────────────────────────────────────────────
const DEFAULT_MAT = {
  preset: '', finish: 'matte', baseColor: '#ffffff',
  holoIntensity: 0, holoScale: 11, bandFreq: 0.48,
  saturation: 1, hueShift: 0, sparkle: 0, specTint: 1,
  iridescence: 0, roughness: 0.85, metalness: 1,
  clearcoat: 1, coatRoughness: 0.3, sheen: 0,
  bump: 0.26, bumpTiling: 2.5,
};
const DEFAULT_PHYS = { gravity: 2.7, damping: 0.9, stiffness: 0.85, rebound: 0, rumple: 0.79, pinMode: 'free-float' };
const DEFAULT_ANIM = { on: true, turbulence: 0.6, speed: 1 };
const DEFAULT_CAM = { rotX: true, rotY: true, pan: true };
// `transmission: 1` mirrors ClothStudio.jsx's DEFAULT_GLASS (the Codex
// glass-transparency round added real optical transparency, orthogonal to
// clarity/roughness) — a recipe captured before that field existed
// normalizes to fully transmissive, exactly like the live scene's `?? 1`.
const DEFAULT_GLASS = { on: false, scale: 1, rotate: true, rotSpeed: 0.4, tint: '#ffffff', clarity: 0.06, transmission: 1, position: [0, 0, 0], rotationOffset: [0, 0, 0] };
// Mirrors elements/primary-cloth.js's DEFAULT_TSHIRT_PRINT exactly (Slice E).
const DEFAULT_TSHIRT_PRINT = { hangerVisible: true, x: 0, y: 0, scale: 1, rotation: 0, opacity: 1 };
// Mirrors ClothStudio.jsx's DEFAULT_DEVICE_PRIMARY exactly (Slice F1) —
// screen-source fields (live/liveUrl/captureUrl/uploadAssetId) default
// EMPTY/off; a non-empty one is precisely capability-rejected until the F2
// pinned-still workflow converts it into a durable content-addressed image.
const DEFAULT_DEVICE_PRIMARY = {
  viewport: 'desktop', captureUrl: '', uploadAssetId: '',
  models: { desktop: 'studio', mobile: 'flagship', tablet: 'pro' },
  finish: 'realistic', claySoftness: 0.85, clayColor: '#e8734a', shellTexture: 'smooth',
  color: '#d6d8da', accent: '#c47c56',
  scroll: false, scrollSpeed: 0.4, scrollPosition: 0,
  sway: false, swaySpeed: 0.5, scale: 1.45,
  seatOnFloor: true, posY: 0,
  live: false, liveUrl: '',
};
const DEVICE_VIEWPORT_IDS = ['desktop', 'mobile', 'tablet'];
const DEFAULT_SHOTCAM = { use: false, az: 24, el: 12, dist: 3.2, fov: 40 };
const DEFAULT_DIFFUSION_CAMERA = {
  enabled: false, locked: false, focalTarget: 'origin',
  focusDistance: 2.2, aperture: 0.4, falloff: 0.5, diffusionRadius: 0.3, highlightBloom: 0.2,
  foregroundBias: 0, backgroundBias: 0,
};
// Mirrors ClothStudio.jsx's DEFAULT_BG_FX exactly (Phase B, Diffusion Camera
// server parity). `diffusion` genuinely feeds the server's uBgDiffusion
// uniform once diffusionCamera.enabled renders through the composer;
// `fit`/`shiftY` stay carried but inert — they only apply once
// bgMode:'image' itself renders, which remains capability-gated (Slice D).
const DEFAULT_BG_FX = { fit: 'cover', shiftY: 0, diffusion: true };
const BG_FX_FIT_IDS = ['cover', 'contain', 'stretch'];
const DEFAULT_FX = {
  bloom: false, bloomStrength: 0.55, bloomThreshold: 0.8, grain: 0, vignette: 0,
  treatment: 'none', t1: 8, t2: 45, t3: 1, colA: '#101014', colB: '#f4f1ea',
};
// LIGHT_TEMPLATES.studio.cans, verbatim.
const DEFAULT_LIGHT_CANS = [
  { on: true, color: '#ffffff', intensity: 1.6, az: 35, el: 40 },
  { on: true, color: '#88ffee', intensity: 0.6, az: -140, el: 15 },
  { on: false, color: '#ffffff', intensity: 1, az: -35, el: 20 },
  { on: false, color: '#ffffff', intensity: 1, az: 180, el: 60 },
];

// ── Numeric bounds — matches the real UI slider min/max declared in
// ClothStudio.jsx (grep'd directly, not guessed) for every field a slider
// actually governs. The reused scene-recipe.js sanitizers only check
// "is this a finite number"; a raw API/template payload isn't constrained by
// a UI slider at all, so this module clamps on top — the "strict numeric
// bounds" this recipe boundary specifically requires that the browser-side
// sanitizers don't (and don't need to, since the browser's own sliders
// already can't produce an out-of-range value). ──────────────────────────
const MAT_BOUNDS = {
  holoIntensity: [0, 1], holoScale: [1, 30], bandFreq: [0, 2], saturation: [0, 1],
  hueShift: [0, 1], sparkle: [0, 1], specTint: [0, 1], iridescence: [0, 1],
  roughness: [0, 1], metalness: [0, 1], clearcoat: [0, 1], coatRoughness: [0, 1],
  sheen: [0, 1], bump: [0, 2], bumpTiling: [1, 12],
};
const PHYS_BOUNDS = { gravity: [0, 4], damping: [0.9, 0.998], stiffness: [0.3, 1], rebound: [0, 1], rumple: [0, 1] };
const ANIM_BOUNDS = { turbulence: [0, 1], speed: [0.2, 3] };
const GLASS_BOUNDS = { scale: [0.4, 2.2], rotSpeed: [0.05, 2], clarity: [0, 0.4], transmission: [0, 1] };
// No UI slider governs glass position/rotationOffset directly (drag-set) —
// bounded defensively since these are spatial offsets a renderer's camera
// math depends on, not because a real UI range is documented for them.
const GLASS_VEC3_BOUND = [-10, 10];
// Scene Lab tweak sliders' real UI min/max (ClothStudio.jsx ~L8830-8871,
// grep'd directly, not guessed) — Slice B/C scene-background parity.
const SCENE_TWEAK_BOUNDS = { panoBlur: [0, 1], panoRotY: [-180, 180], panoIntensity: [0.2, 2], groundY: [-1.15, -0.55], fogDensity: [0.01, 0.2] };
// tshirtPrint sliders' real UI min/max (ClothStudio.jsx ~L8223-8227) — Slice E.
const TSHIRT_PRINT_BOUNDS = { x: [-0.3, 0.3], y: [-0.3, 0.3], scale: [0.4, 1.8], rotation: [-180, 180], opacity: [0, 1] };
// devicePrimary sliders' real UI min/max (ClothStudio.jsx ~L8320-8429) — Slice F1.
const DEVICE_PRIMARY_BOUNDS = { claySoftness: [0.4, 1], scale: [0.8, 2.2], posY: [-0.8, 0.8], scrollSpeed: [0.05, 2], swaySpeed: [0.05, 2], scrollPosition: [0, 1] };
const SHOTCAM_BOUNDS = { az: [-180, 180], el: [-80, 85], dist: [1.2, 8], fov: [20, 90] };
const LIGHT_CAN_BOUNDS = { intensity: [0, 3], az: [-180, 180], el: [-80, 85] };
const DIFFUSION_CAMERA_BOUNDS = {
  focusDistance: [0.5, 4.5], aperture: [0, 1], falloff: [0, 1], diffusionRadius: [0, 1],
  highlightBloom: [0, 1], foregroundBias: [-1, 1], backgroundBias: [-1, 1],
};
const FX_BOUNDS = { bloomStrength: [0, 2], bloomThreshold: [0, 1], grain: [0, 1], vignette: [0, 1] };
// t1/t2/t3 mean different things per TREATMENTS entry (ClothStudio.jsx's own
// per-treatment `params` table declares distinct ranges per slot, e.g.
// halftone's t1 is 3-30 "dot size" but scanline's t1 is 60-1200 "line
// count"). Replicating all 13 treatments' per-slot bounds is a rendering-
// time concern (4c+), not this recipe-validation boundary's job; this broad
// bound is a superset of every real per-treatment range and exists only to
// reject pathological values (1e20, -1e20), not to enforce per-treatment
// precision.
const FX_GENERIC_SLOT_BOUND = [-10, 1200];
const ENV_INTENSITY_BOUNDS = [0, 2.5];

function clamp(value, [min, max]) {
  return Math.min(max, Math.max(min, value));
}

function clampFields(obj, bounds) {
  const out = { ...obj };
  Object.entries(bounds).forEach(([key, range]) => {
    if (isFiniteNum(out[key])) out[key] = clamp(out[key], range);
  });
  return out;
}

class ArtRecipeValidationError extends Error {
  constructor(message, status = 400) {
    super(message);
    this.name = 'ArtRecipeValidationError';
    this.status = status;
  }
}

// Defensive size cap — same rationale/limit as api/_lib/studio-templates.cjs's
// own recipe cap: an oversized payload is either abuse or a client bug,
// rejected before any further processing.
const MAX_SERIALIZED_LENGTH = 200_000;

function isPlainObject(v) {
  return Boolean(v) && typeof v === 'object' && !Array.isArray(v);
}

// Recursively freezes every object/array reachable from `value` — the
// top-level result, `recipe`, every nested field object (mat/phys/anim/cam/
// glass/shotCam/diffusionCamera/fx), `lightCans` and each can, `extraInstances`
// and every instance's own nested transform/material/motion/appearance/
// formatOverrides/random objects, `support`, and `warnings` (the array and
// each entry object). Only ever called on freshly-constructed output objects
// (never on `raw`/`payload` — every field above is built via spread/map/
// dedicated normalize functions that already return new objects, so this
// never reaches back into, or freezes, anything the caller passed in).
function deepFreeze(value) {
  if (value === null || typeof value !== 'object' || Object.isFrozen(value)) return value;
  Object.freeze(value);
  Object.values(value).forEach(deepFreeze);
  return value;
}

function pickEnum(value, allowlist, fallback) {
  return allowlist.includes(value) ? value : fallback;
}

// Capability-DETECTION only, not a real sanitizer — deliberately does not
// import/duplicate app/dashboard/studio/text-layers.js's full
// sanitizeTextLayers (fontId/color/anim/backdrop/etc.), because nothing in
// this render pass draws text yet (art-scene.mjs has no text-canvas/overlay
// compositing at all). checkCapabilities' 'textLayers' entry only needs to
// know whether any layer is visually ON; a request that reaches this
// function with a non-empty "on" set is always rejected before a job is
// ever created (see app/api/dashboard/proof-render/route.js), so no
// unvalidated field value from `raw` is ever persisted. A future slice that
// implements real hero-text rendering must replace this with the real
// sanitizer (vendored, same pattern as scene-recipe.js) instead of building
// on this stub.
const MAX_TEXT_LAYERS_RECIPE = 3; // mirrors text-layers.js's MAX_TEXT_LAYERS
function detectTextLayers(raw) {
  if (!Array.isArray(raw)) return [];
  return raw.slice(0, MAX_TEXT_LAYERS_RECIPE)
    .filter(isPlainObject)
    .map((layer) => ({ on: layer.on !== false }));
}

/**
 * Sanitize the Scene Lab's per-scene tweak overrides (Slice B/C — Codex
 * constraint: "normalize and sanitize sceneTweaks; don't silently omit
 * them"). Field-PRESENCE is semantic (composeSceneDef distinguishes absent
 * from set — an absent field keeps the preset value, `pano: ''` REMOVES the
 * preset's plate), so this returns ONLY the keys that survive validation —
 * never fills defaults, never carries an unknown key or invalid value
 * (which would otherwise let a raw payload smuggle an arbitrary pano path
 * into asset resolution; pano/groundTex are strict allowlist-or-empty).
 */
function sanitizeSceneTweaks(raw) {
  if (!isPlainObject(raw)) return {};
  const out = {};
  Object.entries(SCENE_TWEAK_BOUNDS).forEach(([key, range]) => {
    if (isFiniteNum(raw[key])) out[key] = clamp(raw[key], range);
  });
  if (isBool(raw.fogOn)) out.fogOn = raw.fogOn;
  ['fogColor', 'ground', 'groundTint'].forEach((key) => {
    if (isHexColor(raw[key])) out[key] = raw[key];
  });
  if (raw.pano === '' || (typeof raw.pano === 'string' && SCENE_PANO_IDS.has(raw.pano))) out.pano = raw.pano;
  if (raw.groundTex === '' || (typeof raw.groundTex === 'string' && GROUND_TEXTURE_IDS.has(raw.groundTex))) out.groundTex = raw.groundTex;
  return out;
}

/**
 * Sanitize the device-primary state (Slice F1). Screen-source fields
 * (live/liveUrl/captureUrl/uploadAssetId) ARE carried — as sanitized plain
 * strings/bools — precisely so the capability layer can reject them by
 * name; render code never consumes them (the page forces the screen to the
 * deterministic placeholder until F2's pinned-still lands). Model ids and
 * shellTexture pass through as bounded plain strings — the page's own
 * normalizeElementInstance applies the catalog fieldSpec allowlists, and
 * deviceResolveModel falls back safely for an unknown id.
 */
// Shape rules for the pinned screen-still reference (Slice F2) — MIRRORS
// api/_lib/studio-screen-stills.cjs's sanitizeScreenStillRef exactly (that
// module re-validates at its own Storage boundary; this recipe boundary
// can't import the CJS module without dragging firebase-admin into the
// pure-ESM recipe graph, so the small rule set is duplicated with a drift
// note on both sides). sha256 is canonical lowercase hex only.
const SCREEN_STILL_EXTS = ['png', 'jpg', 'webp'];
const SCREEN_STILL_DIMENSION_RANGE = [16, 8192];
const SCREEN_STILL_MAX_BYTES = 8 * 1024 * 1024;
const SCREEN_STILL_MAX_PIXELS = 32 * 1024 * 1024; // mirrors the lib's MAX_TOTAL_PIXELS decoded-pixel budget
function sanitizeScreenStillShape(raw) {
  if (!isPlainObject(raw)) return null;
  const okDim = (v) => Number.isInteger(v) && v >= SCREEN_STILL_DIMENSION_RANGE[0] && v <= SCREEN_STILL_DIMENSION_RANGE[1];
  if (typeof raw.sha256 !== 'string' || !/^[0-9a-f]{64}$/.test(raw.sha256)) return null;
  if (!SCREEN_STILL_EXTS.includes(raw.ext)) return null;
  if (!okDim(raw.width) || !okDim(raw.height)) return null;
  if (raw.width * raw.height > SCREEN_STILL_MAX_PIXELS) return null;
  if (!Number.isInteger(raw.bytes) || raw.bytes <= 0 || raw.bytes > SCREEN_STILL_MAX_BYTES) return null;
  return { sha256: raw.sha256, ext: raw.ext, width: raw.width, height: raw.height, bytes: raw.bytes };
}

/**
 * Sanitize the Background presentation card's fx (Phase B — previously
 * documented as inert-and-uncarried, but never actually implemented; see
 * this function's own call site for why that was a real gap once
 * diffusionCamera genuinely renders). `shiftY` mirrors the real Scene tab
 * UI slider bound (ClothStudio.jsx ~L9268, min -1 max 1).
 */
function sanitizeBgFx(raw) {
  const out = { ...DEFAULT_BG_FX };
  if (!isPlainObject(raw)) return out;
  out.fit = pickEnum(raw.fit, BG_FX_FIT_IDS, out.fit);
  if (isFiniteNum(raw.shiftY)) out.shiftY = clamp(raw.shiftY, [-1, 1]);
  if (isBool(raw.diffusion)) out.diffusion = raw.diffusion;
  return out;
}

function sanitizeDevicePrimary(raw) {
  const out = { ...DEFAULT_DEVICE_PRIMARY, models: { ...DEFAULT_DEVICE_PRIMARY.models } };
  if (!isPlainObject(raw)) return out;
  out.viewport = pickEnum(raw.viewport, DEVICE_VIEWPORT_IDS, out.viewport);
  if (isPlainObject(raw.models)) {
    // Allowlisted against each viewport's REAL model family (Codex F1 P1
    // correction — length-capping alone let '__proto__'-class ids through
    // to prototype-chain lookups downstream). An unknown/malicious id
    // simply keeps that viewport's default model.
    DEVICE_VIEWPORT_IDS.forEach((vp) => {
      const id = raw.models[vp];
      if (typeof id === 'string' && Object.hasOwn(DEVICE_MODELS, vp) && Object.hasOwn(DEVICE_MODELS[vp], id)) {
        out.models[vp] = id;
      }
    });
  }
  out.finish = pickEnum(raw.finish, ['realistic', 'clay'], out.finish);
  if (typeof raw.shellTexture === 'string' && Object.hasOwn(DEVICE_SHELL_TEXTURES, raw.shellTexture)) {
    out.shellTexture = raw.shellTexture;
  }
  ['color', 'accent', 'clayColor'].forEach((k) => { if (isHexColor(raw[k])) out[k] = raw[k]; });
  Object.entries(DEVICE_PRIMARY_BOUNDS).forEach(([k, range]) => {
    if (isFiniteNum(raw[k])) out[k] = clamp(raw[k], range);
  });
  ['scroll', 'sway', 'seatOnFloor', 'live'].forEach((k) => { if (isBool(raw[k])) out[k] = raw[k]; });
  ['captureUrl', 'uploadAssetId', 'liveUrl'].forEach((k) => {
    if (typeof raw[k] === 'string') out[k] = raw[k].slice(0, 2048);
  });
  // Recovery round 2 (Defect 1) added `captureSourceUrl`/`captureViewport`
  // to the CLIENT's devicePrimary shape (capture provenance — which site/
  // viewport captureUrl is actually an image of, consulted by the Quick
  // Export live guard and the pin planner in elements/video-export.js).
  // Deliberately NOT carried here: this render pass already never reads
  // captureUrl itself (every raw screen-source field is capability-gated
  // above render code, and force-cleared in the instance the renderer
  // actually builds — see art-scene.mjs), so provenance ABOUT captureUrl
  // has nothing to govern server-side either. Any raw payload's
  // captureSourceUrl/captureViewport keys are silently dropped by this
  // function's own explicit allowlist (the same "unknown keys never pass
  // through" behavior every other field here already has) — never carried
  // into the normalized recipe, so a timeline keyframe can never differ on
  // them (art-timeline.mjs's diff simply never sees a key that isn't here).
  // Pinned screen still (Slice F2): a VALID reference carries; a PRESENT
  // but malformed one is flagged (never silently dropped — dropping it
  // would render the shell with the placeholder as if nothing was pinned,
  // exactly the "sourced screen silently rendered blank" outcome the F2
  // contract forbids; the flag becomes a precise capability rejection).
  if (raw.screenStill !== undefined) {
    const still = sanitizeScreenStillShape(raw.screenStill);
    if (still) out.screenStill = still;
    else out.screenStillInvalid = true;
  }
  return out;
}

/**
 * Normalize one `art-scene-v2` scene payload (the untrusted, ClothStudio-
 * captureSceneRecipe-shaped object) into a fully validated recipe. Never
 * throws on a malformed FIELD — invalid/missing fields fall back to the
 * documented default, same "degrade a field, never reject the whole object"
 * discipline as elements/scene-recipe.js itself. Returns `{ recipe, support,
 * warnings }`; never mutates `raw`.
 *
 * Fields intentionally NOT carried into art-scene-v2 (see the Slice 4a
 * checkpoint's field table for the full rationale): `hudOn` (editor-only HUD
 * overlay toggle, never present in an exported/rendered frame),
 * `elementLocks` and `randomizeIntensity` (both pure randomize-editor UI
 * state with zero effect on what a scene actually renders as).
 *
 * `tshirtPrint` IS carried since Slice E (clothShape 'tshirt' genuinely
 * renders) — shared sanitizeTshirtPrint + exact print-slider UI bounds.
 * `devicePrimary` IS carried since Slice F1 (the device SHELL with its
 * deterministic placeholder screen renders; screen-source fields are
 * carried sanitized so the capability layer can reject each by name until
 * F2's pinned-still conversion exists — render code never reads them).
 * `bgFx` IS carried since Phase B (Diffusion Camera server parity) — it was
 * previously documented as "inert, needs no capability check" but was
 * never actually normalized/carried at all, which would have silently
 * dropped `bgFx.diffusion` the moment diffusionCamera started genuinely
 * rendering (the exact "accepted but silently omitted" defect this recipe
 * boundary exists to prevent). `bgFx.diffusion` now genuinely feeds the
 * server's uBgDiffusion uniform whenever diffusionCamera.enabled renders;
 * `bgFx.fit`/`shiftY` stay carried but inert — they only apply once
 * `bgMode==='image'` renders, which remains capability-gated
 * ('background-image', Slice D) — so bgFx still needs no capability check
 * of its own, but for a genuinely-checked reason now, not an unverified one.
 *
 * `sceneTweaks` IS carried since the Slice B/C scene-parity pass (it used
 * to be dropped as inert while every `bgMode!=='color'` was blanket-gated):
 * `bgMode==='scene'` renders now, tweaks compose into the effective scene
 * (composeSceneDef), and capability is judged from that COMPOSED result —
 * a tweak can add or remove a pano/groundTex requirement, so dropping
 * tweaks would make "supported" a lie in both directions.
 */
function normalizeScene(raw) {
  const r = isPlainObject(raw) ? raw : {};
  const warnings = [];

  const mat = clampFields(sanitizeMat(r.mat, DEFAULT_MAT, { finishes: FINISHES, presetIds: MATERIAL_PRESET_IDS }), MAT_BOUNDS);
  const phys = clampFields(sanitizePhys(r.phys, DEFAULT_PHYS, { pinModeIds: PIN_MODE_IDS }), PHYS_BOUNDS);
  const anim = clampFields(sanitizeAnim(r.anim, DEFAULT_ANIM), ANIM_BOUNDS);
  const cam = sanitizeCam(r.cam, DEFAULT_CAM);
  const lightCans = sanitizeLightCans(r.lightCans, DEFAULT_LIGHT_CANS)
    .map((can) => clampFields(can, LIGHT_CAN_BOUNDS));
  const lightTemplate = (LIGHT_TEMPLATE_IDS.includes(r.lightTemplate) || r.lightTemplate === '') ? r.lightTemplate : 'studio';
  const glassSanitized = sanitizeGlass(r.glass, DEFAULT_GLASS);
  const glass = {
    ...clampFields(glassSanitized, GLASS_BOUNDS),
    position: glassSanitized.position.map((v) => clamp(v, GLASS_VEC3_BOUND)),
    rotationOffset: glassSanitized.rotationOffset.map((v) => clamp(v, GLASS_VEC3_BOUND)),
  };
  const shotCam = clampFields(sanitizeShotCam(r.shotCam, DEFAULT_SHOTCAM), SHOTCAM_BOUNDS);
  const diffusionCamera = clampFields(sanitizeDiffusionCamera(r.diffusionCamera, DEFAULT_DIFFUSION_CAMERA), DIFFUSION_CAMERA_BOUNDS);
  const camSeed = Number.isFinite(r.camSeed) ? r.camSeed : 1;
  // frameId (Capture Frame parity round): a MISSING id defaults to 'off',
  // but a PRESENT-yet-unknown id is flagged, never silently normalized to
  // 'off' — the user selected a crop; rendering the full canvas instead
  // would silently change their output (capability gate 'frame-unknown').
  const frameId = FRAME_PRESET_IDS.includes(r.frameId) ? r.frameId : 'off';
  const frameIdInvalid = r.frameId != null && !FRAME_PRESET_IDS.includes(r.frameId) ? true : undefined;
  // The live stage's aspect at capture time (Capture Frame parity round) —
  // the frame crop's COMPOSITION depends on the stage it is cut from
  // (computeFrameRect insets the crop into the live canvas), so a framed
  // deterministic render must pin the aspect the user actually composed
  // against. Bounded to sane display shapes; absent (old recipes) → 16:9.
  const stageAspect = isFiniteNum(r.stageAspect) ? clamp(r.stageAspect, [0.3, 4]) : 16 / 9;
  const envId = pickEnum(r.envId, ENV_PRESET_IDS, 'room');
  const fxSanitized = clampFields(sanitizeFx(r.fx, DEFAULT_FX, { treatmentIds: TREATMENT_IDS }), FX_BOUNDS);
  const fx = clampFields(fxSanitized, { t1: FX_GENERIC_SLOT_BOUND, t2: FX_GENERIC_SLOT_BOUND, t3: FX_GENERIC_SLOT_BOUND });
  const fxPresetId = (FX_PRESET_IDS.includes(r.fxPresetId) || r.fxPresetId === '') ? r.fxPresetId : '';
  const clothAspect = (CLOTH_ASPECT_IDS.includes(r.clothAspect) || r.clothAspect === 'auto') ? r.clothAspect : 'auto';
  const clothShape = pickEnum(r.clothShape, CLOTH_SHAPE_IDS, 'sheet');
  const tshirtPrint = clampFields(sanitizeTshirtPrint(r.tshirtPrint, DEFAULT_TSHIRT_PRINT), TSHIRT_PRINT_BOUNDS);
  const devicePrimary = sanitizeDevicePrimary(r.devicePrimary);
  const bgFx = sanitizeBgFx(r.bgFx);
  const textLayers = detectTextLayers(r.textLayers);
  const artworkRatio = (isFiniteNum(r.artworkRatio) || r.artworkRatio == null) ? (r.artworkRatio ?? null) : null;

  let artworkId = DEFAULT_ARTWORK_ID;
  if (typeof r.artworkId === 'string' && r.artworkId) {
    if (BUILTIN_ARTWORK_IDS.includes(r.artworkId)) {
      artworkId = r.artworkId;
    } else {
      // A custom/local artwork lives only in that ONE browser's own
      // localStorage artwork library (ClothStudio.jsx's ARTWORK_LIB_KEY) —
      // it was never uploaded anywhere this server can see. Falling back
      // to the default built-in is the honest behavior; silently accepting
      // the id would let a future render step construct a lookup/path from
      // a value that can never resolve to real image data server-side.
      warnings.push({
        field: 'artworkId', code: 'unsupported-custom-artwork',
        message: `artworkId "${r.artworkId}" is not one of this service's built-in artworks (browser-local custom artwork is not representable server-side); defaulted to "${DEFAULT_ARTWORK_ID}".`,
      });
    }
  }

  const bgMode = pickEnum(r.bgMode, BG_MODES, 'color');
  const bgColor = isHexColor(r.bgColor) ? r.bgColor : '#000000';
  const sceneId = pickEnum(r.sceneId, SCENE_PRESET_IDS, 'thriller');
  const sceneTweaks = sanitizeSceneTweaks(r.sceneTweaks);
  const envIntensity = isFiniteNum(r.envIntensity) ? clamp(r.envIntensity, ENV_INTENSITY_BOUNDS) : 0.65;

  let videoSeconds = 5;
  if (VIDEO_SECONDS_OPTIONS.includes(r.videoSeconds)) {
    videoSeconds = r.videoSeconds;
  } else if (isFiniteNum(r.videoSeconds) && r.videoSeconds > 0) {
    warnings.push({
      field: 'videoSeconds', code: 'unsupported-duration',
      message: `videoSeconds ${r.videoSeconds} is not one of this service's supported durations (${VIDEO_SECONDS_OPTIONS.join(', ')}); defaulted to 5.`,
    });
  }
  const videoFormat = pickEnum(r.videoFormat, VIDEO_FORMAT_IDS, 'mp4');
  const perf = pickEnum(r.perf, PERF_LEVEL_IDS, 'high');
  const sceneSeed = Number.isFinite(r.sceneSeed) ? r.sceneSeed : 1;
  const lookSeed = Number.isFinite(r.lookSeed) ? r.lookSeed : 1;

  // Element ordering is preserved exactly as submitted — restoreExtraInstances
  // dedups by id first-occurrence-wins, in original array order, never
  // sorting/reversing; that's the "normalized element ordering" this
  // function's own determinism guarantee rests on.
  const extraInstances = restoreExtraInstances(r.extraInstances, { primaryId: PRIMARY_ELEMENT_ID, maxCount: MAX_EXTRA_INSTANCES });

  const elementFormatId = PLACEMENT_FORMATS[r.elementFormatId] ? r.elementFormatId : 'landscape';
  const elementQualityTier = LIVE_PREVIEW_TIERS.includes(r.elementQualityTier) ? r.elementQualityTier : 'draft';

  const recipe = {
    perf, mat, phys, anim, cam, lightCans, lightTemplate, glass, shotCam, diffusionCamera, camSeed,
    frameId, ...(frameIdInvalid ? { frameIdInvalid } : {}), stageAspect,
    envId, fx, fxPresetId, clothAspect, clothShape, tshirtPrint, devicePrimary, artworkRatio, artworkId,
    bgMode, bgColor, bgFx, sceneId, sceneTweaks, envIntensity, videoSeconds, videoFormat, sceneSeed, lookSeed,
    extraInstances, elementFormatId, elementQualityTier, textLayers,
  };

  return { recipe, warnings };
}

/**
 * Validate + normalize a full `art-scene-v2` request payload:
 * `{ kind, schemaVersion, scene }`. Throws ArtRecipeValidationError (with a
 * `.status`, 400 for every case here) for anything structurally wrong —
 * not a plain object, wrong/missing `kind`, wrong/missing `schemaVersion`,
 * a non-object `scene`, or an oversized payload. Never trusts (and never
 * copies through) any field outside this function's own explicit output
 * shape — render dimensions, output/storage paths, ownership, billing, job
 * status, or infrastructure settings a caller might smuggle into the
 * payload are silently absent from the result, not merely unvalidated.
 */
export function normalizeArtSceneRecipe(payload) {
  if (!isPlainObject(payload)) {
    throw new ArtRecipeValidationError('payload must be a plain object.');
  }
  if (payload.kind !== RECIPE_KIND) {
    throw new ArtRecipeValidationError(`Unsupported recipe kind: ${payload.kind}. Expected "${RECIPE_KIND}".`);
  }
  if (payload.schemaVersion !== RECIPE_SCHEMA_VERSION) {
    throw new ArtRecipeValidationError(`Unsupported schema version: ${payload.schemaVersion}. Expected ${RECIPE_SCHEMA_VERSION}.`);
  }
  if (!isPlainObject(payload.scene)) {
    throw new ArtRecipeValidationError('payload.scene must be a plain object.');
  }

  let serialized;
  try { serialized = JSON.stringify(payload.scene); } catch { throw new ArtRecipeValidationError('payload.scene must be JSON-serializable.'); }
  if (serialized.length > MAX_SERIALIZED_LENGTH) {
    throw new ArtRecipeValidationError('payload.scene is too large.');
  }

  const { recipe, warnings } = normalizeScene(payload.scene);

  return deepFreeze({
    kind: RECIPE_KIND,
    schemaVersion: RECIPE_SCHEMA_VERSION,
    primaryElementId: PRIMARY_ELEMENT_ID,
    recipe,
    // Phase B (Diffusion Camera server parity, STUDIO-DETERMINISTIC-FINAL-
    // RENDER-SONNET-HANDOFF.md) — art-scene.mjs now genuinely renders the
    // two-pass diffusion/treatment composer chain (vendored verbatim from
    // ClothStudio.jsx's own DIFFUSION_SHADER/TREATMENT_SHADER) whenever
    // diffusionCamera.enabled is true; the CAPABILITY_CHECKS gate in
    // art-render-validation.mjs was removed to match. This flag is carried
    // for API-response provenance only — checkCapabilities is the actual
    // enforcement point a caller must honor.
    support: { diffusionCamera: true },
    warnings,
  });
}

export { ArtRecipeValidationError };
