#!/usr/bin/env node
/**
 * Generate a human-readable review doc for the active X algorithm profile.
 * Usage: node scripts/review-x-algo.mjs
 * Output: docs/x-algo-review.md
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'module';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, '..');

const ACTIVE_PROFILE_ID = 'x-2026-05-15';
const require = createRequire(import.meta.url);
const profile = require(`../features/x-growth/algorithm-profiles/${ACTIVE_PROFILE_ID}.json`);

const reviewedAt = profile.reviewedAt || 'unknown';
const sources = (profile.sources || []).map((s) => `- ${s}`).join('\n');

const assumptionsBlock = Object.entries(profile.assumptions || {})
  .map(([key, a]) => {
    return `### ${key}\n- **Confidence:** ${a.confidence}\n- **Hypothesis:** ${a.hypothesis}${a.suggestedWorkaround ? `\n- **Workaround:** ${a.suggestedWorkaround}` : ''}`;
  })
  .join('\n\n');

const positiveActions = (profile.predictedActions?.positive || [])
  .map((a) => `| \`${a.id}\` | ${a.description} |`)
  .join('\n');
const negativeActions = (profile.predictedActions?.negative || [])
  .map((a) => `| \`${a.id}\` | ${a.description} |`)
  .join('\n');

const postTypeHints = Object.entries(profile.postTypeScoringHints || {})
  .map(([type, h]) => `| \`${type}\` | \`${h.primaryAction}\` | \`${h.secondaryAction}\` |`)
  .join('\n');

const markdown = `# X Algorithm Review

**Profile ID:** \`${profile.id}\`
**Reviewed at:** ${reviewedAt}
**Note:** ${profile.note || ''}

---

## Sources

${sources || '_none_'}

---

## Predicted Phoenix Actions

### Positive signals
| Action | Description |
|--------|-------------|
${positiveActions}

### Negative signals
| Action | Description |
|--------|-------------|
${negativeActions}

---

## Assumptions

${assumptionsBlock || '_none documented_'}

---

## Post Type Scoring Hints

| Post Type | Primary Action | Secondary Action |
|-----------|---------------|-----------------|
${postTypeHints}

---

## Human Review Checklist

- [ ] Sources above still resolve and content has not changed significantly
- [ ] Confidence labels reflect current understanding (high/medium/low)
- [ ] Any new assumptions from community research or X announcements added
- [ ] Post type hints still match observed engagement patterns
- [ ] Profile \`reviewedAt\` updated to today's date after completing this review
- [ ] If significant changes: increment profile ID (e.g. \`x-2026-08-01\`) and update \`algorithm-profile.js\`

_Generated by \`npm run review:x-algo\` on ${new Date().toISOString().slice(0, 10)}_
`;

const outDir = path.join(REPO_ROOT, 'docs');
await fs.mkdir(outDir, { recursive: true });
const outPath = path.join(outDir, 'x-algo-review.md');
await fs.writeFile(outPath, markdown, 'utf8');
console.log(`Written: ${outPath}`);
